server:
  port: 8085
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/preclinical

  mail:
    from: ticket-office@myboxoffice.info
    host: email-smtp.us-east-1.amazonaws.com
    username: AKIATQXZTZO7EGKYULM7
    password: BI6UJdoumXb5mMD6BBdITHxxw/BF240/xDuHigH1X6V1
    port: 465
    properties:
      mail.smtp.host: email-smtp.us-east-1.amazonaws.com
      mail.smtp.ssl.enable: true
    templates-path: templates/

  thymeleaf:
    enabled: false

  file-service:
    path: src/main/resources/uploaded-files/
    path-delimiter: \\
    domain: http://localhost:8080/
  storage:
    type: FILE_SYSTEM

  output:
    ansi:
      enabled: always


properties:
  baseUrl: http://localhost:8080/


jwt:
  issuer: auth
  access-expiration-in-ms: 1800000
  refresh-expiration-in-ms: 3600000
  alias: prgxKey
  certificate: prgxKey.jks
  store-password: prgxpass
  key-password: prgxpass
  secret: 68?Rctu2?_p}Hh8}&=|j!dSVh,en).=SQA6&U+BSx/Fhs84kdg5.V'y;G8Es.9S8NH9Th}~8Bd4yc_Mi

cloud:
  aws:
    credentials:
      accessKey: test
      secretKey: test
    region: eu-west-1
    bucket: test
