server:
  port: 8080
#  servlet:
#    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chiriezerie?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    hikari:
      connection-timeout: 600000

  jpa:
    show_sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  data:
    web:
      pageable:
        size-parameter: size
        page-parameter: page
        default-page-size: 10
        one-indexed-parameters: false
        max-page-size: 2000

  flyway:
    baseline-on-migrate: true
    baseline-version: 1.0.0
    locations:  classpath:db/migration
    validate-on-migrate: true

jwt:
  issuer: auth
  access-expiration-in-ms: 180000
  refresh-expiration-in-ms: 3600000
  alias: prgxKey
  certificate: prgxKey.jks
  store-password: prgxpass
  key-password: prgxpass
  secret: 68?Rctu2?_p}Hh8}&=|j!dSVh,en).=SQA6&U+BSx/Fhs84kdg5.V'y;G8Es.9S8NH9Th}~8Bd4yc_Mi
