server:
  port: 8080
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/preclinical

  mail:
    host: smtp.gmail.com
    port: 587
    username: xqtpos@gmail.com
    password: Worldbank123
    properties.mail.smtp:
      socketFactory.port: 465
      socketFactory.class: javax.net.ssl.SSLSocketFactory
      socketFactory.fallback: false
      auth: true
      ssl.enable: true
      starttls.enable: false

  thymeleaf:
    enabled: false

  file-service:
    path: src/main/resources/uploaded-files/
    path-delimiter: \\
    domain: http://localhost:8080/
  storage:
    type: FILE_SYSTEM

  output:
    ansi:
      enabled: always


properties:
  baseUrl: http://localhost:8080/


jwt:
  issuer: auth
  access-expiration-in-ms: 1800000
  refresh-expiration-in-ms: 3600000
  alias: prgxKey
  certificate: prgxKey.jks
  store-password: prgxpass
  key-password: prgxpass
  secret: 68?Rctu2?_p}Hh8}&=|j!dSVh,en).=SQA6&U+BSx/Fhs84kdg5.V'y;G8Es.9S8NH9Th}~8Bd4yc_Mi

cloud:
  aws:
    credentials:
      accessKey: test
      secretKey: test
    region: eu-west-1
    bucket: test
